apiVersion: v2
name: epiphany-stack
description: A Helm chart for epiphany-stack
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 18.0.5
    repository: file://subcharts/kube-prometheus-stack

  - name: fluentd
    version: 4.4.1
    repository: file://subcharts/fluentd

  # - name: base
  #   version: 1.12.0-beta.2
  #   repository: file://subcharts/base

  # - name: istiod
  #   version: 1.12.0-beta.2
  #   repository: file://subcharts/istiod

  # - name: istio-ingress
  #   version: 1.0.0
  #   repository: file://subcharts/istio-ingress

  # - name: istio-egress
  #   version: 1.0.0
  #   repository: file://subcharts/istio-egress

  # - name: elasticsearch
  #   version: 7.15.0
  #   repository: file://subcharts/elasticsearch

  # - name: fluentd-elasticsearch
  #   version: 13.1.0
  #   repository: file://subcharts/fluentd-elasticsearch

  # - name: kibana
  #   version: 7.14.0
  #   repository: file://subcharts/kibana

  # - name: keycloak
  #   version: 15.0.2
  #   repository: file://subcharts/keycloak

  # - name: kafka
  #   version: 14.2.0
  #   repository: file://subcharts/kafka

  # - name: rabbitmq
  #   version: 8.22.4
  #   repository: file://subcharts/rabbitmq

  # - name: vault
  #   version:  0.17.1
  #   repository: file://subcharts/vault-helm-0.17.1

